begin;
select plan(13);
insert into auth.users(id,email) values('33333333-3333-4333-8333-333333333333','verdict@example.com');
insert into public.investigation_sessions(id,user_id,case_id,case_version) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','33333333-3333-4333-8333-333333333333','midnight-ledger',1);
set local role authenticated;
set local request.jwt.claim.sub='33333333-3333-4333-8333-333333333333';
select throws_ok($$select * from private.case_solutions$$,'42501',null,'solution keys are private');
select throws_ok($$insert into public.accusations(session_id,user_id,suspect_id,evidence_ids) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),'mara-vale',array['glove-fiber-report','full-camera-review'])$$,'23514',null,'cannot skip deductions');
reset role;
update public.investigation_sessions set solved_deduction_ids=array['deduce-access','deduce-alibis'] where id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
set local role authenticated;
select throws_ok($$insert into public.accusations(session_id,user_id,suspect_id,evidence_ids,is_correct) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),'mara-vale',array['glove-fiber-report','full-camera-review'],true)$$,'42501',null,'cannot forge verdict');
select throws_ok($$insert into public.accusations(session_id,user_id,suspect_id,evidence_ids) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),'mara-vale',array['glove-fiber-report','glove-fiber-report'])$$,'23514',null,'duplicate evidence rejected');
select throws_ok($$insert into public.accusations(session_id,user_id,suspect_id,evidence_ids) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),'unknown',array['glove-fiber-report','full-camera-review'])$$,'23514',null,'unknown suspect rejected');
set local request.jwt.claim.sub='44444444-4444-4444-8444-444444444444';
select throws_ok($$insert into public.accusations(session_id,user_id,suspect_id,evidence_ids) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),'mara-vale',array['glove-fiber-report','full-camera-review'])$$,'42501',null,'cannot close another users session');
set local request.jwt.claim.sub='33333333-3333-4333-8333-333333333333';
select lives_ok($$insert into public.accusations(session_id,user_id,suspect_id,evidence_ids) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),'mara-vale',array['full-camera-review','glove-fiber-report'])$$,'correct accusation accepted in either evidence order');
select is((select is_correct from public.accusations),true,'database computes correct verdict');
select is((select status from public.investigation_sessions),'completed','session closed atomically');
select throws_ok($$insert into public.accusations(session_id,user_id,suspect_id,evidence_ids) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',auth.uid(),'mara-vale',array['full-camera-review','glove-fiber-report'])$$,'42501',null,'cannot resubmit final verdict');
select throws_ok($$update public.accusations set suspect_id='ellis-rook'$$,'42501',null,'cannot edit verdict');
set local request.jwt.claim.sub='44444444-4444-4444-8444-444444444444';
select is_empty($$select * from public.accusations$$,'other users cannot read result');
reset role;
insert into public.investigation_sessions(id,user_id,case_id,case_version,solved_deduction_ids) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','33333333-3333-4333-8333-333333333333','midnight-ledger',1,array['deduce-access','deduce-alibis']);
set local role authenticated;
set local request.jwt.claim.sub='33333333-3333-4333-8333-333333333333';
insert into public.accusations(session_id,user_id,suspect_id,evidence_ids) values('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',auth.uid(),'ellis-rook',array['full-camera-review','glove-fiber-report']);
select is((select is_correct from public.accusations where session_id='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'),false,'wrong suspect records an incorrect verdict');
select * from finish();
rollback;
