import type { MysteryCase } from "../schema";

export const midnightLedger: MysteryCase = {
  schemaVersion: 2,
  id: "midnight-ledger",
  version: 1,
  truth: {
    title: "The Midnight Ledger",
    setting: "The closed reading room of the Bellwether Hotel, 11:40 p.m.",
    suspects: [
      {
        id: "mara-vale",
        name: "Mara Vale",
        publicBio: "The hotel's archivist, responsible for the reading room collection.",
        secret: "She planned to sell a page that tied her family to the hotel's first owner.",
      },
      {
        id: "ellis-rook",
        name: "Ellis Rook",
        publicBio: "A financial reporter researching the Bellwether's original investors.",
        secret: "He had promised an editor a story before confirming his source.",
      },
      {
        id: "nora-quill",
        name: "Nora Quill",
        publicBio: "The night manager overseeing staff and guest access.",
        secret: "She had concealed a costly inventory mistake from the hotel owner.",
      },
    ],
    culpritId: "mara-vale",
    motive: "Mara needed the ledger page before a reporter could publish its connection to her family.",
    method: "She used her archive key, removed the ledger, and hid it in a document tube before raising the alarm.",
    timeline: [
      {
        id: "ellis-call",
        minute: 5,
        actorIds: ["ellis-rook"],
        fact: "Ellis began a recorded lobby landline call that continued through the theft window.",
      },
      {
        id: "nora-cage",
        minute: 8,
        actorIds: ["nora-quill"],
        fact: "Nora entered the basement supply cage and remained on its camera through the theft window.",
      },
      {
        id: "reading-room-locked",
        minute: 10,
        actorIds: [],
        fact: "At 11:30 p.m., the closing inventory confirmed the ledger present and the reading room locked. Timeline minutes are measured from 11:20 p.m.",
      },
      {
        id: "mara-entry",
        minute: 20,
        actorIds: ["mara-vale"],
        fact: "Mara opened the reading room with the archive key assigned to her.",
      },
      {
        id: "ledger-removed",
        minute: 25,
        actorIds: ["mara-vale"],
        fact: "Mara removed the ledger and caught her glove on the document cabinet.",
      },
      {
        id: "alarm-raised",
        minute: 30,
        actorIds: ["mara-vale", "nora-quill"],
        fact: "At 11:50 p.m., Mara reported the ledger missing over the hotel intercom; Nora heard the alarm while still in the supply cage.",
      },
    ],
    proofPlan: {
      crimeWindow: "The ledger disappeared between the 11:30 lock check and the 11:50 alarm.",
      culpritEvidence: "The archive key log identifies Mara's entry, while matching glove fibers place her at the opened cabinet.",
      exclusions: [
        {
          suspectId: "ellis-rook",
          eventIds: ["ellis-call"],
          observableProof: "The timestamped landline recording and lobby camera cover Ellis for the full theft window.",
        },
        {
          suspectId: "nora-quill",
          eventIds: ["nora-cage"],
          observableProof: "The supply-cage badge log and continuous camera footage cover Nora for the full theft window.",
        },
      ],
    },
    explanation: "Mara alone entered with a valid key during the theft window, and fibers from her torn archive glove were caught where the ledger was removed.",
  },
  dossier: {
    opening: "The closing inventory confirmed the century-old ledger present and the reading room locked at 11:30 p.m. At 11:50 p.m., the alarm was raised: the ledger was missing. The theft occurred during that twenty-minute window. Three people remained in the building.",
    difficulty: "easy",
    estimatedMinutes: 20,
    evidence: [
      {
        id: "archive-key-log",
        title: "Archive Key Log",
        kind: "record",
        content: "11:40 p.m. - Archive key A-3 opened the reading room. A-3 is signed out to Mara Vale.",
        source: "Bellwether electronic lock system",
        eventIds: ["mara-entry"],
        releaseAfterDeductionId: null,
        openingDelivery: "shared",
      },
      {
        id: "lobby-call-record",
        title: "Lobby Call Record",
        kind: "audio-transcript",
        content: "The lobby landline recorded Ellis speaking continuously from 11:25 p.m. until 11:52 p.m.",
        source: "Bellwether switchboard archive",
        eventIds: ["ellis-call"],
        releaseAfterDeductionId: null,
        openingDelivery: "shared",
      },
      {
        id: "supply-cage-record",
        title: "Supply Cage Record",
        kind: "record",
        content: "Nora badged into the basement cage at 11:28 p.m. Camera review shows her inside until 11:53 p.m.",
        source: "Staff access report",
        eventIds: ["nora-cage"],
        releaseAfterDeductionId: null,
        openingDelivery: "shared",
      },
      {
        id: "cabinet-snag",
        title: "Cabinet Snag",
        kind: "photo-description",
        content: "A dark green thread is caught on the brass latch of the cabinet where the ledger was stored.",
        source: "Investigator's scene photograph",
        eventIds: ["ledger-removed"],
        releaseAfterDeductionId: null,
        openingDelivery: "shared",
      },
      {
        id: "glove-fiber-report",
        title: "Glove Fiber Report",
        kind: "record",
        content: "The thread is the same wool blend and dye lot as Mara's torn archive gloves.",
        source: "Hotel conservator's comparison",
        eventIds: ["ledger-removed"],
        releaseAfterDeductionId: "deduce-access",
        openingDelivery: "shared",
      },
      {
        id: "full-camera-review",
        title: "Full Camera Review",
        kind: "record",
        content: "Lobby and basement recordings have no gaps: Ellis and Nora remain visible throughout the 11:30-11:50 theft window.",
        source: "Security office review",
        eventIds: ["ellis-call", "nora-cage"],
        releaseAfterDeductionId: "deduce-alibis",
        openingDelivery: "shared",
      },
    ],
    deductions: [
      {
        id: "deduce-access",
        question: "Whose documented access is consistent with the cabinet trace?",
        requiredEvidenceIds: ["archive-key-log", "cabinet-snag"],
        choices: [
          { id: "access-mara", label: "Mara Vale" },
          { id: "access-ellis", label: "Ellis Rook" },
          { id: "access-nora", label: "Nora Quill" },
        ],
        correctChoiceId: "access-mara",
        explanation: "Mara's assigned key opened the room, and the cabinet snag suggests contact by someone handling archival material.",
        hints: ["Start with the lock record.", "Compare authorized access with the physical trace.", "Key A-3 belongs to Mara."],
      },
      {
        id: "deduce-alibis",
        question: "Which two alibis are independently recorded for the entire theft window?",
        requiredEvidenceIds: ["lobby-call-record", "supply-cage-record"],
        choices: [
          { id: "alibis-ellis-nora", label: "Ellis and Nora" },
          { id: "alibis-mara-ellis", label: "Mara and Ellis" },
          { id: "alibis-mara-nora", label: "Mara and Nora" },
        ],
        correctChoiceId: "alibis-ellis-nora",
        explanation: "Separate systems continuously place Ellis in the lobby and Nora in the basement.",
        hints: ["Look for records covering a span, not a single moment.", "Two systems track two different locations.", "The call and cage records cover Ellis and Nora."],
      },
    ],
    accusation: {
      requiredEvidenceIds: ["glove-fiber-report", "full-camera-review"],
      culpritProof: "Mara's key and matching glove fiber independently connect her to the locked room and opened cabinet.",
      exclusions: [
        {
          suspectId: "ellis-rook",
          evidenceIds: ["lobby-call-record", "full-camera-review"],
          explanation: "The recording and camera place Ellis outside the reading room for the full window.",
        },
        {
          suspectId: "nora-quill",
          evidenceIds: ["supply-cage-record", "full-camera-review"],
          explanation: "The access report and camera place Nora in the basement for the full window.",
        },
      ],
    },
  },
};